"""Safe, hash-bound activation for the Living Wiki projection.

The projector deliberately recomputes all candidate pages.  This module only
decides which already-generated bytes need to become live and records enough
state to recover an interrupted activation deterministically.
"""

from __future__ import annotations

import json
import os
import shutil
import uuid
from collections.abc import Callable
from pathlib import Path, PurePosixPath
from typing import Any

from ..knowledge_autonomy import _atomic_owner_write, _validate_contract
from ..util import canonical_json, sha256_bytes, sha256_file, strict_json_loads

CHANGE_SET_SCHEMA = "deeplaw.living-wiki-change-set/v2"
JOURNAL_SCHEMA = "deeplaw.living-wiki-projection-journal/v2"
LEGACY_CHANGE_SET_SCHEMA = "deeplaw.living-wiki-change-set/v1"
LEGACY_JOURNAL_SCHEMA = "deeplaw.living-wiki-projection-journal/v1"
JOURNAL_NAME = "living-wiki-projection.journal.json"
MANIFEST_NAME = "living-wiki-manifest.json"
V3_MANIFEST_NAME = ".deeplaw/derived/wiki/v3/manifest.json"
V3_NAMESPACE = ".deeplaw/derived/wiki/v3/"
_MAX_FILES = 1_000_000
_MAX_JOURNAL_BYTES = 64 * 1024 * 1024
# The v2 contract permits a bounded million-entry inventory, and the canonical
# rebuild path already enforces the same 64 MiB local manifest ceiling.  Keep
# incremental activation aligned so a valid standard-profile manifest does not
# become unreadable just above 1 MiB.
_MAX_MANIFEST_BYTES = 64 * 1024 * 1024
_MAX_PAYLOAD_BYTES = 256 * 1024
_TXN_ROOT = PurePosixPath(".deeplaw/derived/tree/.projection-transactions")
_ALLOWED_PREFIXES = ("wiki/", "canvas/", V3_NAMESPACE)


def _journal_has_v3(journal: dict[str, Any]) -> bool:
    return journal.get("schema_version") == JOURNAL_SCHEMA and all(
        field in journal
        for field in (
            "old_v3_manifest_sha256",
            "new_v3_manifest_sha256",
            "old_inventory_sha256",
            "new_inventory_sha256",
            "v3_manifest_path",
        )
    )


def _safe_relative(value: str, *, allow_manifest: bool = False) -> str:
    if not isinstance(value, str) or not value or "\x00" in value:
        raise RuntimeError("Living Wiki projection path is invalid")
    path = PurePosixPath(value)
    if path.is_absolute() or not path.parts or any(
        part in {"", ".", ".."} for part in path.parts
    ):
        raise RuntimeError("Living Wiki projection path is unsafe")
    normalized = path.as_posix()
    if allow_manifest and normalized in {
        MANIFEST_NAME,
        ".deeplaw/derived/tree/living-wiki-manifest.json",
        V3_MANIFEST_NAME,
    }:
        return normalized
    if not normalized.startswith(_ALLOWED_PREFIXES):
        raise RuntimeError("Living Wiki projection path escaped wiki/canvas")
    return normalized


def _safe_transaction_relative(value: str) -> PurePosixPath:
    if not isinstance(value, str) or "\x00" in value:
        raise RuntimeError("Living Wiki transaction path is invalid")
    path = PurePosixPath(value)
    root = _TXN_ROOT
    if path.is_absolute() or not path.parts or path.parts[: len(root.parts)] != root.parts:
        raise RuntimeError("Living Wiki transaction path escaped the Vault")
    if any(part in {"", ".", ".."} for part in path.parts):
        raise RuntimeError("Living Wiki transaction path is unsafe")
    if len(path.parts) != len(root.parts) + 2 or path.parts[-1] not in {"staging", "backup"}:
        raise RuntimeError("Living Wiki transaction path has invalid depth")
    return path


def _lstat(path: Path) -> os.stat_result | None:
    try:
        return path.lstat()
    except FileNotFoundError:
        return None


def _check_root(root: Path) -> None:
    stat = _lstat(root)
    if stat is None or not stat or not os.path.isdir(root):
        raise RuntimeError("DeepLaw Vault root is missing or unsafe")
    if os.path.islink(root):
        raise RuntimeError("DeepLaw Vault root must not be a symbolic link")


def _check_ancestors(root: Path, relative: str, *, create: bool = False) -> Path:
    """Check each component without resolving symlinks.

    On POSIX, opening each directory with ``O_NOFOLLOW`` closes the common
    symlink-ancestor gap while the path is inspected.  The lstat checks are
    retained for Windows and for a clear fail-closed error on all platforms.
    """

    _check_root(root)
    path = PurePosixPath(relative)
    if path.is_absolute() or any(part in {"", ".", ".."} for part in path.parts):
        raise RuntimeError("Living Wiki path is unsafe")
    current = root
    fd: int | None = None
    try:
        if os.name != "nt":
            flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_NOFOLLOW", 0)
            fd = os.open(root, flags)
        for part in path.parts[:-1]:
            current = current / part
            stat = _lstat(current)
            if stat is not None and (os.path.islink(current) or not os.path.isdir(current)):
                raise RuntimeError("Living Wiki path has an unsafe ancestor")
            if stat is None:
                if not create:
                    continue
                current.mkdir(mode=0o700)
                stat = _lstat(current)
            if stat is None or os.path.islink(current) or not os.path.isdir(current):
                raise RuntimeError("Living Wiki path has an unsafe ancestor")
            if fd is not None:
                next_fd = os.open(part, flags, dir_fd=fd)
                os.close(fd)
                fd = next_fd
        return current
    finally:
        if fd is not None:
            os.close(fd)


def _check_file(root: Path, relative: str, *, allow_missing: bool = True) -> Path:
    relative = _safe_relative(relative, allow_manifest=True)
    parent = _check_ancestors(root, relative, create=False)
    path = root / relative
    stat = _lstat(path)
    if stat is None:
        if allow_missing:
            return path
        raise RuntimeError("Living Wiki projection file is missing")
    if os.path.islink(path) or not os.path.isfile(path):
        raise RuntimeError("Living Wiki projection file is unsafe")
    del parent
    return path


def _mkdir_safe(root: Path, relative: str) -> Path:
    parts = PurePosixPath(relative).parts
    if not parts:
        raise RuntimeError("Living Wiki transaction directory is invalid")
    _check_ancestors(root, relative + "/placeholder", create=True)
    path = root / relative
    stat = _lstat(path)
    if stat is None:
        path.mkdir(mode=0o700)
    elif os.path.islink(path) or not os.path.isdir(path):
        raise RuntimeError("Living Wiki transaction directory is unsafe")
    return path


def _atomic_json(path: Path, value: dict[str, Any]) -> None:
    payload = (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode(
        "utf-8"
    )
    _atomic_owner_write(path, payload)


def _read_json(path: Path, *, max_bytes: int = _MAX_JOURNAL_BYTES) -> dict[str, Any] | None:
    stat = _lstat(path)
    if stat is None:
        return None
    if os.path.islink(path) or not os.path.isfile(path) or stat.st_size > max_bytes:
        raise RuntimeError("Living Wiki transaction metadata is unsafe")
    try:
        value = strict_json_loads(path.read_bytes())
    except (OSError, UnicodeDecodeError, ValueError, json.JSONDecodeError) as exc:
        raise RuntimeError("Living Wiki transaction metadata is invalid") from exc
    if not isinstance(value, dict):
        raise RuntimeError("Living Wiki transaction metadata must be an object")
    return value


def _descriptor(value: Any, *, old: bool = False) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise RuntimeError("Living Wiki file descriptor is invalid")
    path = _safe_relative(value.get("path"))
    digest_key = "old_sha256" if old else "sha256"
    size_key = "old_byte_size" if old else "byte_size"
    digest = value.get(digest_key)
    size = value.get(size_key)
    if not isinstance(digest, str) or len(digest) != 64 or any(
        char not in "0123456789abcdef" for char in digest
    ):
        raise RuntimeError("Living Wiki file descriptor hash is invalid")
    limit = _MAX_MANIFEST_BYTES if path.endswith("/manifest.json") else _MAX_PAYLOAD_BYTES
    if path == V3_MANIFEST_NAME:
        limit = _MAX_MANIFEST_BYTES
    if not isinstance(size, int) or isinstance(size, bool) or not 0 <= size <= limit:
        raise RuntimeError("Living Wiki file descriptor size is invalid")
    return {"path": path, size_key: size, digest_key: digest}


def _manifest_hash(manifest: dict[str, Any]) -> str:
    body = {key: value for key, value in manifest.items() if key != "manifest_sha256"}
    digest = manifest.get("manifest_sha256")
    expected = sha256_bytes(canonical_json(body).encode("utf-8"))
    if not isinstance(digest, str) or digest != expected:
        raise RuntimeError("Living Wiki manifest hash is invalid")
    return digest


def _v3_descriptor(path: str, data: bytes) -> dict[str, Any]:
    _safe_relative(path, allow_manifest=True)
    limit = _MAX_MANIFEST_BYTES if path.endswith("/manifest.json") else _MAX_PAYLOAD_BYTES
    if path == V3_MANIFEST_NAME:
        limit = _MAX_MANIFEST_BYTES
    if len(data) > limit:
        raise RuntimeError("Living Wiki v3 artifact exceeds its byte bound")
    return {"path": path, "byte_size": len(data), "sha256": sha256_bytes(data)}


def _read_v3_snapshot(root: Path, *, required: bool = False) -> dict[str, Any] | None:
    """Read and verify the manifest-declared v3 bundle without scanning directories."""

    from ..wiki.registry import _safe_read_file

    top_path = root / V3_MANIFEST_NAME
    stat = _lstat(top_path)
    if stat is None:
        if required:
            raise RuntimeError("Living Wiki v3 manifest is missing")
        return None
    if (
        os.path.islink(top_path)
        or not os.path.isfile(top_path)
        or stat.st_size > _MAX_MANIFEST_BYTES
    ):
        raise RuntimeError("Living Wiki v3 manifest is unsafe")
    try:
        top_raw = _safe_read_file(
            root,
            V3_MANIFEST_NAME,
            max_bytes=_MAX_MANIFEST_BYTES,
            field="Living Wiki v3 manifest",
        )
        top = strict_json_loads(top_raw)
    except (OSError, UnicodeDecodeError, ValueError, json.JSONDecodeError) as error:
        raise RuntimeError("Living Wiki v3 manifest is invalid") from error
    if not isinstance(top, dict):
        raise RuntimeError("Living Wiki v3 manifest must be an object")
    try:
        from ..wiki.registry import validate_living_wiki_manifest_v3

        validate_living_wiki_manifest_v3(top)
    except Exception as error:
        raise RuntimeError("Living Wiki v3 manifest is invalid") from error
    top_hash = _manifest_hash(top)
    # A readable v3 bundle is only admissible as the active pair when its declared v2 hash
    # matches the same root's authoritative tree manifest.  Staging roots carry that manifest at
    # their root; live roots carry it under .deeplaw/derived/tree.
    v2_candidates = [
        root / ".deeplaw" / "derived" / "tree" / MANIFEST_NAME,
        root / MANIFEST_NAME,
    ]
    found_v2 = False
    for v2_path in v2_candidates:
        if _lstat(v2_path) is None:
            continue
        relative_v2 = (
            ".deeplaw/derived/tree/living-wiki-manifest.json"
            if v2_path == root / ".deeplaw" / "derived" / "tree" / MANIFEST_NAME
            else MANIFEST_NAME
        )
        try:
            v2_raw = _safe_read_file(
                root,
                relative_v2,
                max_bytes=_MAX_MANIFEST_BYTES,
                field="Living Wiki v2 manifest",
            )
            v2_value = strict_json_loads(v2_raw)
            if not isinstance(v2_value, dict):
                raise RuntimeError("Living Wiki v2 manifest is invalid")
            _validate_contract("living-wiki-manifest.v2.schema.json", v2_value)
            if _manifest_hash(v2_value) != top["v2_manifest_sha256"]:
                raise RuntimeError("Living Wiki v2/v3 manifest pair is inconsistent")
        except (OSError, UnicodeDecodeError, ValueError, json.JSONDecodeError) as error:
            raise RuntimeError("Living Wiki v2 manifest is invalid") from error
        found_v2 = True
        break
    if not found_v2:
        raise RuntimeError("Living Wiki v3 manifest has no authoritative v2 pair")
    descriptors = [_v3_descriptor(V3_MANIFEST_NAME, top_raw)]
    try:
        from ..wiki.link_index import load_link_index
        from ..wiki.registry import load_page_registry
        from ..wiki.resolver import load_resolver

        registry = load_page_registry(root, top)
        links = load_link_index(root, top, registry)
        resolver = load_resolver(root, top, registry)
    except Exception as error:
        raise RuntimeError("Living Wiki v3 component verification failed") from error
    components: dict[str, dict[str, Any]] = {
        "page_registry": registry,
        "link_index": links,
        "resolver": resolver,
    }
    # Inventory is the transitive owner set: top manifest, each component manifest, and every
    # shard/coverage shard declared by those component manifests.  The v2 manifest remains the
    # owner of its own wiki/canvas files; no path is duplicated here.
    for descriptor in top["components"]:
        component_name = descriptor["component"]
        manifest_path = descriptor["manifest_path"]
        manifest_raw = _safe_read_file(
            root,
            manifest_path,
            max_bytes=_MAX_MANIFEST_BYTES,
            field="Living Wiki v3 component manifest",
        )
        component = (
            strict_json_loads(manifest_raw)
            if component_name == "resolver"
            else components[component_name]["component"]
        )
        descriptors.append(_v3_descriptor(manifest_path, manifest_raw))
        for key in ("shards", "coverage_shards"):
            for shard in component.get(key, []):
                path = shard["path"]
                raw = _safe_read_file(
                    root,
                    path,
                    max_bytes=_MAX_PAYLOAD_BYTES,
                    field="Living Wiki v3 shard",
                )
                descriptors.append(_v3_descriptor(path, raw))
    descriptors.sort(key=lambda row: row["path"])
    paths = [row["path"] for row in descriptors]
    if len(paths) != len(set(paths)):
        raise RuntimeError("Living Wiki v3 inventory paths overlap")
    return {
        "manifest": top,
        "manifest_sha256": top_hash,
        "files": descriptors,
        "inventory_sha256": sha256_bytes(canonical_json(descriptors).encode("utf-8")),
        "components": components,
    }


def read_previous_v3(root: Path) -> dict[str, Any] | None:
    return _read_v3_snapshot(root)


def _read_v3_top_hash(root: Path) -> str | None:
    """Read only the active top hash for crash-state classification.

    During activation the top may already point at the new bundle while component shards are
    still old (or vice versa).  Recovery must classify that pair without treating the transient
    mixed bundle as a valid readable index.
    """

    path = root / V3_MANIFEST_NAME
    stat = _lstat(path)
    if stat is None:
        return None
    if os.path.islink(path) or not os.path.isfile(path) or stat.st_size > _MAX_MANIFEST_BYTES:
        raise RuntimeError("Living Wiki v3 manifest is unsafe")
    try:
        value = strict_json_loads(path.read_bytes())
        if not isinstance(value, dict):
            raise ValueError("manifest must be an object")
        return _manifest_hash(value)
    except (OSError, UnicodeDecodeError, ValueError, json.JSONDecodeError) as error:
        raise RuntimeError("Living Wiki v3 top manifest is invalid") from error


def read_previous_manifest(root: Path) -> dict[str, Any] | None:
    """Read and validate the authoritative previous manifest, if present."""

    manifest_path = root / ".deeplaw/derived/tree" / MANIFEST_NAME
    _check_ancestors(
        root,
        ".deeplaw/derived/tree/living-wiki-manifest.json",
        create=False,
    )
    if _lstat(manifest_path) is None:
        return None
    if os.path.islink(manifest_path) or not os.path.isfile(manifest_path):
        raise RuntimeError("Living Wiki manifest is missing or unsafe")
    value = _read_json(manifest_path)
    if value is None:
        return None
    schema = value.get("schema_version")
    contract = {
        "deeplaw.living-wiki-manifest/v1": "living-wiki-manifest.v1.schema.json",
        "deeplaw.living-wiki-manifest/v2": "living-wiki-manifest.v2.schema.json",
    }.get(schema)
    if contract is None:
        raise RuntimeError("Living Wiki previous manifest schema is unsupported")
    _manifest_hash(value)
    try:
        _validate_contract(contract, value)
    except Exception as exc:
        raise RuntimeError("Living Wiki previous manifest is invalid") from exc
    files = value.get("files")
    if not isinstance(files, list) or len(files) > _MAX_FILES:
        raise RuntimeError("Living Wiki previous manifest inventory is invalid")
    paths: set[str] = set()
    for item in files:
        if not isinstance(item, dict) or set(item) != {"path", "byte_size", "sha256"}:
            raise RuntimeError("Living Wiki previous manifest file descriptor is invalid")
        path = _safe_relative(item["path"])
        if path in paths:
            raise RuntimeError("Living Wiki previous manifest has duplicate paths")
        paths.add(path)
        _descriptor(item)
    if files != sorted(files, key=lambda item: item["path"]):
        raise RuntimeError("Living Wiki previous manifest inventory is not sorted")
    return value


def _manifest_files(manifest: dict[str, Any] | None) -> dict[str, dict[str, Any]]:
    if not manifest:
        return {}
    return {item["path"]: item for item in manifest.get("files", [])}


def _snapshot_files(
    manifest: dict[str, Any] | None,
    v3_snapshot: dict[str, Any] | None,
) -> dict[str, dict[str, Any]]:
    files = _manifest_files(manifest)
    if v3_snapshot is not None:
        for item in v3_snapshot.get("files", []):
            path = item["path"]
            if path in files:
                raise RuntimeError("Living Wiki v2/v3 inventory paths overlap")
            files[path] = item
    return files


def build_change_set(
    previous: dict[str, Any] | None,
    current: dict[str, Any],
    *,
    previous_v3: dict[str, Any] | None = None,
    current_v3: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Return a deterministic hash-level change set.

    This is intentionally a content-hash diff, not a dependency graph.  A page
    is considered touched only when its live bytes change.
    """

    old = _snapshot_files(previous, previous_v3)
    new = _snapshot_files(current, current_v3)
    created: list[dict[str, Any]] = []
    updated: list[dict[str, Any]] = []
    deleted: list[dict[str, Any]] = []
    unchanged: list[dict[str, Any]] = []
    for path in sorted(set(old) | set(new)):
        old_item = old.get(path)
        new_item = new.get(path)
        if old_item is None:
            created.append(_descriptor(new_item))
        elif new_item is None:
            deleted.append(
                {
                    "path": _safe_relative(path),
                    "old_byte_size": old_item["byte_size"],
                    "old_sha256": old_item["sha256"],
                }
            )
        elif (
            old_item["sha256"] == new_item["sha256"]
            and old_item["byte_size"] == new_item["byte_size"]
        ):
            unchanged.append(_descriptor(new_item))
        else:
            updated.append(
                {
                    "path": _safe_relative(path),
                    "old_byte_size": old_item["byte_size"],
                    "old_sha256": old_item["sha256"],
                    "byte_size": new_item["byte_size"],
                    "sha256": new_item["sha256"],
                }
            )
    total_count = len(created) + len(updated) + len(deleted) + len(unchanged)
    if total_count > _MAX_FILES:
        raise RuntimeError("Living Wiki change set exceeds its bound")
    configuration = current.get("configuration")
    if not isinstance(configuration, dict):
        raise RuntimeError("Living Wiki manifest configuration is invalid")
    profile = configuration.get("projection_profile")
    if not isinstance(profile, dict):
        raise RuntimeError("Living Wiki projection profile is invalid")
    result: dict[str, Any] = {
        "schema_version": CHANGE_SET_SCHEMA,
        "old_manifest_sha256": previous.get("manifest_sha256") if previous else None,
        "new_manifest_sha256": current["manifest_sha256"],
        "old_v3_manifest_sha256": previous_v3.get("manifest_sha256") if previous_v3 else None,
        "new_v3_manifest_sha256": current_v3.get("manifest_sha256") if current_v3 else None,
        "old_inventory_sha256": previous_v3.get("inventory_sha256") if previous_v3 else None,
        "new_inventory_sha256": current_v3.get("inventory_sha256") if current_v3 else None,
        "input_audit_head": current["input_audit_head"],
        "legacy_audit_head": current["legacy_audit_head"],
        "projection_profile_name": profile["name"],
        "projection_profile_sha256": configuration["projection_profile_sha256"],
        "created": created,
        "updated": updated,
        "deleted": deleted,
        "unchanged": unchanged,
        "total_count": total_count,
        "truncated": False,
        "truncation_reason": None,
    }
    result["change_set_sha256"] = sha256_bytes(canonical_json(result).encode("utf-8"))
    _validate_contract("living-wiki-change-set.v2.schema.json", result)
    return result


def _legacy_change_set(previous: dict[str, Any] | None, current: dict[str, Any]) -> dict[str, Any]:
    """Reconstruct the frozen v1 change-set shape for legacy journal recovery only."""

    modern = build_change_set(previous, current)
    legacy = {
        key: value
        for key, value in modern.items()
        if key
        not in {
            "old_v3_manifest_sha256",
            "new_v3_manifest_sha256",
            "old_inventory_sha256",
            "new_inventory_sha256",
        }
    }
    legacy["schema_version"] = LEGACY_CHANGE_SET_SCHEMA
    legacy.pop("change_set_sha256", None)
    legacy["change_set_sha256"] = sha256_bytes(canonical_json(legacy).encode("utf-8"))
    _validate_contract("living-wiki-change-set.v1.schema.json", legacy)
    return legacy


def _journal_body(journal: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in journal.items() if key != "journal_sha256"}


def _seal_journal(journal: dict[str, Any]) -> dict[str, Any]:
    sealed = dict(journal)
    sealed["journal_sha256"] = sha256_bytes(
        canonical_json(_journal_body(sealed)).encode("utf-8")
    )
    contract = (
        "living-wiki-projection-journal.v2.schema.json"
        if sealed.get("schema_version") == JOURNAL_SCHEMA
        else "living-wiki-projection-journal.v1.schema.json"
    )
    _validate_contract(contract, sealed)
    return sealed


def _validate_journal(journal: dict[str, Any]) -> None:
    schema = journal.get("schema_version")
    if schema == JOURNAL_SCHEMA and _journal_has_v3(journal):
        _validate_contract("living-wiki-projection-journal.v2.schema.json", journal)
    elif schema in {LEGACY_JOURNAL_SCHEMA, JOURNAL_SCHEMA}:
        legacy = dict(journal)
        legacy["schema_version"] = LEGACY_JOURNAL_SCHEMA
        legacy.pop("journal_sha256", None)
        legacy["journal_sha256"] = journal.get("journal_sha256")
        _validate_contract("living-wiki-projection-journal.v1.schema.json", legacy)
    else:
        raise RuntimeError("Living Wiki projection journal schema is unsupported")
    expected = sha256_bytes(canonical_json(_journal_body(journal)).encode("utf-8"))
    if journal.get("journal_sha256") != expected:
        raise RuntimeError("Living Wiki projection journal hash is invalid")
    staging = _safe_transaction_relative(journal["staging_path"])
    backup = _safe_transaction_relative(journal["backup_path"])
    staging_txn = staging.parts[-2]
    backup_txn = backup.parts[-2]
    if (
        journal["transaction_id"] != staging_txn
        or staging_txn != backup_txn
    ):
        raise RuntimeError("Living Wiki transaction identity binding is invalid")
    _safe_relative(journal["manifest_path"], allow_manifest=True)
    if _journal_has_v3(journal) and journal.get("v3_manifest_path") != V3_MANIFEST_NAME:
        raise RuntimeError("Living Wiki v3 manifest journal binding is invalid")
    paths: list[str] = []
    for key in ("created", "updated", "deleted"):
        entries = journal[key]
        entry_paths = [item["path"] for item in entries]
        if entry_paths != sorted(entry_paths) or len(entry_paths) != len(set(entry_paths)):
            raise RuntimeError("Living Wiki journal file inventory is not sorted and unique")
        paths.extend(entry_paths)
    if len(paths) != len(set(paths)):
        raise RuntimeError("Living Wiki journal file inventory overlaps")


def _journal_path(root: Path) -> Path:
    return root / ".deeplaw/derived/tree" / JOURNAL_NAME


def _transaction_root(root: Path, txn_id: str) -> Path:
    if not isinstance(txn_id, str) or not txn_id or "/" in txn_id or "\\" in txn_id:
        raise RuntimeError("Living Wiki transaction identity is invalid")
    relative = f"{_TXN_ROOT.as_posix()}/{txn_id}"
    _check_ancestors(root, relative + "/placeholder", create=True)
    path = root / relative
    stat = _lstat(path)
    if stat is None:
        path.mkdir(mode=0o700)
    elif os.path.islink(path) or not os.path.isdir(path):
        raise RuntimeError("Living Wiki transaction directory is unsafe")
    return path


def begin_transaction(root: Path) -> tuple[str, Path, Path]:
    """Create a bounded staging and backup pair without touching live outputs."""

    _check_root(root)
    journal = _journal_path(root)
    if _lstat(journal) is not None:
        raise RuntimeError("Living Wiki projection has an unresolved transaction")
    txn_id = uuid.uuid4().hex
    staging = _transaction_root(root, txn_id) / "staging"
    backup = _transaction_root(root, txn_id) / "backup"
    staging.mkdir(mode=0o700)
    backup.mkdir(mode=0o700)
    return txn_id, staging, backup


def _verify_descriptor(path: Path, descriptor: dict[str, Any], *, old: bool = False) -> None:
    digest_key = "old_sha256" if old else "sha256"
    size_key = "old_byte_size" if old else "byte_size"
    stat = _lstat(path)
    if stat is None or os.path.islink(path) or not os.path.isfile(path):
        raise RuntimeError("Living Wiki owned file is missing or unsafe")
    if stat.st_size != descriptor[size_key] or sha256_file(path) != descriptor[digest_key]:
        raise RuntimeError("Living Wiki owned file hash/size does not match its manifest")


def _copy_file(source: Path, destination: Path, expected: dict[str, Any]) -> None:
    if os.path.islink(source) or not source.is_file():
        raise RuntimeError("Living Wiki staging file is missing or unsafe")
    _verify_descriptor(source, expected)
    parent = destination.parent
    parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    _atomic_owner_write(destination, source.read_bytes())


def _remove_empty_transaction(root: Path, txn_id: str) -> None:
    if not isinstance(txn_id, str) or not txn_id or "/" in txn_id or "\\" in txn_id:
        raise RuntimeError("Living Wiki transaction cleanup identity is unsafe")
    base = root / _TXN_ROOT / txn_id
    if base.parent != root / _TXN_ROOT:
        raise RuntimeError("Living Wiki transaction cleanup path is unsafe")
    if _lstat(base) is None:
        return
    if os.path.islink(base) or not base.is_dir():
        raise RuntimeError("Living Wiki transaction cleanup path is unsafe")
    shutil.rmtree(base)


def _cleanup_journal(root: Path, journal: dict[str, Any]) -> None:
    txn_id = PurePosixPath(journal["staging_path"]).parts[-2]
    _remove_empty_transaction(root, txn_id)
    transaction_container = root / _TXN_ROOT
    if _lstat(transaction_container) is not None:
        if os.path.islink(transaction_container) or not transaction_container.is_dir():
            raise RuntimeError("Living Wiki transaction container is unsafe")
        if not any(transaction_container.iterdir()):
            transaction_container.rmdir()
    path = _journal_path(root)
    _check_ancestors(root, ".deeplaw/derived/tree/living-wiki-projection.journal.json")
    stat = _lstat(path)
    if stat is not None:
        if os.path.islink(path) or not os.path.isfile(path):
            raise RuntimeError("Living Wiki journal path is unsafe")
        path.unlink()


def _staging_file(staging: Path, relative: str) -> Path:
    relative = _safe_relative(relative)
    parent = _check_ancestors(staging, relative, create=False)
    del parent
    return staging / relative


def _validate_staging(
    root: Path,
    journal: dict[str, Any],
    manifest: dict[str, Any],
    v3_snapshot: dict[str, Any] | None = None,
) -> None:
    _check_ancestors(root, journal["staging_path"] + "/living-wiki-manifest.json")
    staging = root / journal["staging_path"]
    stat = _lstat(staging)
    if stat is None or os.path.islink(staging) or not os.path.isdir(staging):
        raise RuntimeError("Living Wiki staging directory is missing or unsafe")
    allowed_files = {item["path"] for item in manifest["files"]} | {MANIFEST_NAME}
    if v3_snapshot is not None:
        allowed_files.update(item["path"] for item in v3_snapshot.get("files", []))
    for candidate in staging.rglob("*"):
        if os.path.islink(candidate):
            raise RuntimeError("Living Wiki staging directory contains a symbolic link")
        if candidate.is_file():
            relative = candidate.relative_to(staging).as_posix()
            if relative not in allowed_files:
                raise RuntimeError("Living Wiki staging directory contains an unexpected file")
    for item in manifest["files"]:
        _verify_descriptor(_staging_file(staging, item["path"]), item)
    if v3_snapshot is not None:
        for item in v3_snapshot.get("files", []):
            _verify_descriptor(_staging_file(staging, item["path"]), item)
    staged_manifest = staging / MANIFEST_NAME
    if _lstat(staged_manifest) is None or os.path.islink(staged_manifest):
        raise RuntimeError("Living Wiki staged manifest is missing or unsafe")
    if strict_json_loads(staged_manifest.read_bytes()) != manifest:
        raise RuntimeError("Living Wiki staged manifest is tampered")
    if v3_snapshot is not None:
        v3_path = staging / V3_MANIFEST_NAME
        if _lstat(v3_path) is None or os.path.islink(v3_path):
            raise RuntimeError("Living Wiki staged v3 manifest is missing or unsafe")
        staged_v3 = strict_json_loads(v3_path.read_bytes())
        if not isinstance(staged_v3, dict) or staged_v3 != v3_snapshot.get("manifest"):
            raise RuntimeError("Living Wiki staged v3 manifest is tampered")


def _new_manifest_from_staging(root: Path, journal: dict[str, Any]) -> dict[str, Any]:
    _check_ancestors(root, journal["staging_path"] + "/living-wiki-manifest.json")
    staging = root / journal["staging_path"]
    manifest_path = staging / MANIFEST_NAME
    value = _read_json(manifest_path)
    if value is None:
        raise RuntimeError("Living Wiki staged manifest is missing")
    _manifest_hash(value)
    _validate_contract("living-wiki-manifest.v2.schema.json", value)
    if value["manifest_sha256"] != journal["new_manifest_sha256"]:
        raise RuntimeError("Living Wiki staged manifest identity mismatch")
    return value


def _new_v3_from_staging(root: Path, journal: dict[str, Any]) -> dict[str, Any] | None:
    if not _journal_has_v3(journal):
        return None
    staging = root / journal["staging_path"]
    snapshot = _read_v3_snapshot(staging, required=True)
    if snapshot is None or snapshot["manifest_sha256"] != journal.get("new_v3_manifest_sha256"):
        raise RuntimeError("Living Wiki staged v3 manifest identity mismatch")
    return snapshot


def _old_files_exact(
    root: Path,
    previous: dict[str, Any] | None,
    previous_v3: dict[str, Any] | None = None,
) -> None:
    for item in _snapshot_files(previous, previous_v3).values():
        path = _check_file(root, item["path"], allow_missing=False)
        _verify_descriptor(path, item)


def _preflight_collisions(
    root: Path,
    previous: dict[str, Any] | None,
    current: dict[str, Any],
    previous_v3: dict[str, Any] | None = None,
    current_v3: dict[str, Any] | None = None,
) -> None:
    old = _snapshot_files(previous, previous_v3)
    new = _snapshot_files(current, current_v3)
    for item in new.values():
        path = _check_file(root, item["path"], allow_missing=True)
        if _lstat(path) is None:
            continue
        if item["path"] not in old:
            raise RuntimeError("Living Wiki projection would overwrite an unowned user file")
        _verify_descriptor(path, old[item["path"]])
    for item in old.values():
        _check_file(root, item["path"], allow_missing=True)
        if _lstat(root / item["path"]) is not None:
            _verify_descriptor(root / item["path"], item)


def _write_journal(root: Path, journal: dict[str, Any]) -> dict[str, Any]:
    sealed = _seal_journal(journal)
    payload = (json.dumps(sealed, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode(
        "utf-8"
    )
    if len(payload) > _MAX_JOURNAL_BYTES:
        raise RuntimeError("Living Wiki projection journal exceeds its byte bound")
    _atomic_json(_journal_path(root), sealed)
    return sealed


def _validate_change_set_binding(
    root: Path,
    journal: dict[str, Any],
    current: dict[str, Any],
    current_v3: dict[str, Any] | None = None,
) -> None:
    previous = read_previous_manifest(root)
    if (previous.get("manifest_sha256") if previous else None) != journal[
        "old_manifest_sha256"
    ]:
        raise RuntimeError("Living Wiki transaction old manifest binding is invalid")
    previous_v3 = read_previous_v3(root) if _journal_has_v3(journal) else None
    expected = (
        _legacy_change_set(previous, current)
        if not _journal_has_v3(journal)
        else build_change_set(
            previous,
            current,
            previous_v3=previous_v3,
            current_v3=current_v3,
        )
    )
    for key in ("created", "updated", "deleted"):
        if expected[key] != journal[key]:
            raise RuntimeError("Living Wiki projection journal change set is tampered")
    if expected["change_set_sha256"] != journal["change_set_sha256"]:
        raise RuntimeError("Living Wiki projection journal change set hash is invalid")


def prepare_activation(
    root: Path,
    *,
    txn_id: str,
    staging: Path,
    backup: Path,
    previous: dict[str, Any] | None,
    current: dict[str, Any],
    change_set: dict[str, Any],
    previous_v3: dict[str, Any] | None = None,
    current_v3: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Validate ownership, copy rollback bytes, and persist the prepare journal."""

    _old_files_exact(root, previous, previous_v3)
    _preflight_collisions(root, previous, current, previous_v3, current_v3)
    _validate_staging(
        root,
        {
            "staging_path": staging.relative_to(root).as_posix(),
            "new_manifest_sha256": current["manifest_sha256"],
        },
        current,
        current_v3,
    )
    for item in [*change_set["updated"], *change_set["deleted"]]:
        old_item = {
            "path": item["path"],
            "byte_size": item["old_byte_size"],
            "sha256": item["old_sha256"],
        }
        source = _check_file(root, item["path"], allow_missing=False)
        _verify_descriptor(source, old_item)
        destination = backup / item["path"]
        _check_ancestors(backup, item["path"], create=True)
        destination.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
        _atomic_owner_write(destination, source.read_bytes())
        _verify_descriptor(destination, old_item)
    journal = {
        "schema_version": JOURNAL_SCHEMA,
        "transaction_id": txn_id,
        "phase": "prepare",
        "old_manifest_sha256": previous.get("manifest_sha256") if previous else None,
        "new_manifest_sha256": current["manifest_sha256"],
        "old_v3_manifest_sha256": previous_v3.get("manifest_sha256") if previous_v3 else None,
        "new_v3_manifest_sha256": current_v3.get("manifest_sha256") if current_v3 else None,
        "old_inventory_sha256": previous_v3.get("inventory_sha256") if previous_v3 else None,
        "new_inventory_sha256": current_v3.get("inventory_sha256") if current_v3 else None,
        "input_audit_head": current["input_audit_head"],
        "legacy_audit_head": current["legacy_audit_head"],
        "projection_profile_sha256": current["configuration"]["projection_profile_sha256"],
        "staging_path": staging.relative_to(root).as_posix(),
        "backup_path": backup.relative_to(root).as_posix(),
        "manifest_path": ".deeplaw/derived/tree/living-wiki-manifest.json",
        "v3_manifest_path": V3_MANIFEST_NAME,
        "created": change_set["created"],
        "updated": change_set["updated"],
        "deleted": change_set["deleted"],
        "change_set_sha256": change_set["change_set_sha256"],
    }
    return _write_journal(root, journal)


def activate_projection(
    root: Path,
    *,
    journal: dict[str, Any],
    current: dict[str, Any],
    fault_hook: Callable[[str], None] | None = None,
) -> None:
    """Apply a prepared transaction and remove its private metadata."""

    _validate_journal(journal)
    current_v3 = _new_v3_from_staging(root, journal)
    _validate_staging(root, journal, current, current_v3)
    _validate_change_set_binding(root, journal, current, current_v3)
    journal = _write_journal(root, {**journal, "phase": "activate"})
    current_with_index = {
        **current,
        "files_by_path": _snapshot_files(current, current_v3),
    }
    count = 0
    try:
        updated_paths = {entry["path"] for entry in journal["updated"]}

        def activate_new(item: dict[str, Any]) -> None:
            nonlocal count
            path = item["path"]
            target = _check_file(root, path, allow_missing=True)
            if path in updated_paths:
                old_item = next(entry for entry in journal["updated"] if entry["path"] == path)
                if _lstat(target) is not None:
                    _verify_descriptor(
                        target,
                        {
                            "path": path,
                            "byte_size": old_item["old_byte_size"],
                            "sha256": old_item["old_sha256"],
                        },
                    )
            elif _lstat(target) is not None:
                raise RuntimeError("Living Wiki activation encountered an unowned file")
            desired = current_with_index["files_by_path"][path]
            if (
                _lstat(target) is None
                or sha256_file(target) != desired["sha256"]
                or target.stat().st_size != desired["byte_size"]
            ):
                _copy_file(
                    source=root / journal["staging_path"] / path,
                    destination=target,
                    expected=desired,
                )
                count += 1
                if count == 1 and fault_hook is not None:
                    fault_hook("partial_activate")

        # Complete every v2 leaf and every v3 component manifest/shard before switching the v3
        # top pointer.  The top is intentionally removed from the lexical batch and activated
        # once below; the v2 authoritative manifest remains the final switch.
        top_changes = []
        for item in sorted([*journal["created"], *journal["updated"]], key=lambda x: x["path"]):
            if item["path"] == V3_MANIFEST_NAME:
                top_changes.append(item)
            else:
                activate_new(item)
        for item in sorted(journal["deleted"], key=lambda x: x["path"]):
            if item["path"] == V3_MANIFEST_NAME:
                top_changes.append(item)
                continue
            target = _check_file(root, item["path"], allow_missing=False)
            _verify_descriptor(
                target,
                {
                    "path": item["path"],
                    "byte_size": item["old_byte_size"],
                    "sha256": item["old_sha256"],
                },
            )
            target.unlink()
            count += 1
        for item in top_changes:
            if item in journal["deleted"]:
                target = _check_file(root, V3_MANIFEST_NAME, allow_missing=False)
                _verify_descriptor(
                    target,
                    {
                        "path": V3_MANIFEST_NAME,
                        "byte_size": item["old_byte_size"],
                        "sha256": item["old_sha256"],
                    },
                )
                target.unlink()
            else:
                activate_new(item)
        if top_changes and fault_hook is not None:
            fault_hook("after_v3_manifest_switch")
        manifest_path = root / journal["manifest_path"]
        if os.path.islink(manifest_path) or (
            _lstat(manifest_path) is not None and not manifest_path.is_file()
        ):
            raise RuntimeError("Living Wiki manifest is unsafe")
        staged_manifest = root / journal["staging_path"] / MANIFEST_NAME
        manifest_payload = staged_manifest.read_bytes()
        existing_manifest = _lstat(manifest_path)
        if (
            existing_manifest is None
            or existing_manifest.st_size != len(manifest_payload)
            or sha256_bytes(manifest_path.read_bytes()) != sha256_bytes(manifest_payload)
        ):
            _atomic_owner_write(manifest_path, manifest_payload)
        journal = _write_journal(root, {**journal, "phase": "cleanup"})
        if fault_hook is not None:
            fault_hook("after_manifest_switch")
        _cleanup_journal(root, journal)
    except BaseException:
        raise


def _rollback_activation(root: Path, journal: dict[str, Any]) -> None:
    _check_ancestors(root, journal["manifest_path"])
    current_path = root / journal["manifest_path"]
    current = _read_json(current_path)
    current_hash = _manifest_hash(current) if current else None
    old_hash = journal["old_manifest_sha256"]
    new_hash = journal["new_manifest_sha256"]
    current_v3_hash = None
    if _journal_has_v3(journal):
        current_v3_hash = _read_v3_top_hash(root)
        new_pair = (new_hash, journal.get("new_v3_manifest_sha256"))
        old_pair = (old_hash, journal.get("old_v3_manifest_sha256"))
        active_pair = (current_hash, current_v3_hash)
        if active_pair == new_pair:
            _finish_cleanup(root, journal)
            return
        transitional_pairs = {
            (old_hash, journal.get("new_v3_manifest_sha256")),
            (new_hash, journal.get("old_v3_manifest_sha256")),
        }
        if active_pair not in {old_pair, *transitional_pairs}:
            raise RuntimeError("Living Wiki transaction has an unknown active manifest pair")
    elif current_hash == new_hash:
        _finish_cleanup(root, journal)
        return
    if not _journal_has_v3(journal) and current_hash != old_hash:
        raise RuntimeError("Living Wiki transaction has an unknown active manifest")
    backup = root / journal["backup_path"]
    staging = root / journal["staging_path"]
    new_manifest = _new_manifest_from_staging(root, journal)
    new_v3 = _new_v3_from_staging(root, journal)
    _validate_staging(root, journal, new_manifest, new_v3)
    for item in [*journal["updated"], *journal["deleted"]]:
        backup_file = backup / item["path"]
        _verify_descriptor(
            backup_file,
            {
                "path": item["path"],
                "byte_size": item["old_byte_size"],
                "sha256": item["old_sha256"],
            },
        )
    # Remove newly-created files only when they still equal the staged bytes;
    # an owner edit is preserved and causes a fail-closed refusal.
    for item in sorted(journal["created"], key=lambda x: x["path"]):
        target = _check_file(root, item["path"], allow_missing=True)
        if _lstat(target) is None:
            continue
        staged = _staging_file(staging, item["path"])
        _verify_descriptor(staged, item)
        try:
            _verify_descriptor(target, item)
        except RuntimeError as exc:
            raise RuntimeError("Living Wiki rollback encountered an owner-modified file") from exc
        target.unlink()
    for item in sorted(journal["updated"], key=lambda x: x["path"]):
        target = _check_file(root, item["path"], allow_missing=False)
        old_descriptor = {
            "path": item["path"],
            "byte_size": item["old_byte_size"],
            "sha256": item["old_sha256"],
        }
        new_descriptor = {
            "path": item["path"],
            "byte_size": item["byte_size"],
            "sha256": item["sha256"],
        }
        try:
            _verify_descriptor(target, old_descriptor)
            continue
        except RuntimeError:
            _verify_descriptor(target, new_descriptor)
        backup_file = backup / item["path"]
        _verify_descriptor(backup_file, old_descriptor)
        _atomic_owner_write(target, backup_file.read_bytes())
    for item in sorted(journal["deleted"], key=lambda x: x["path"]):
        target = _check_file(root, item["path"], allow_missing=True)
        if _lstat(target) is not None:
            _verify_descriptor(
                target,
                {
                    "path": item["path"],
                    "byte_size": item["old_byte_size"],
                    "sha256": item["old_sha256"],
                },
            )
            continue
        backup_file = backup / item["path"]
        _verify_descriptor(backup_file, {
            "path": item["path"], "byte_size": item["old_byte_size"], "sha256": item["old_sha256"]
        })
        _copy_file(
            backup_file,
            target,
            {
                "path": item["path"],
                "byte_size": item["old_byte_size"],
                "sha256": item["old_sha256"],
            },
        )
    if _journal_has_v3(journal):
        # Restore or remove the v3 top manifest according to the old pair.  Component artifacts
        # are already handled by the same union inventory loops above.
        old_v3_hash = journal.get("old_v3_manifest_sha256")
        current_v3_hash = _read_v3_top_hash(root)
        if old_v3_hash is None:
            if current_v3_hash is not None:
                path = root / V3_MANIFEST_NAME
                if current_v3_hash == journal.get("new_v3_manifest_sha256"):
                    path.unlink()
        elif current_v3_hash != old_v3_hash:
            raise RuntimeError("Living Wiki rollback cannot restore the old v3 manifest pair")
    # The live tree is coherent again, so the full old bundle can now be loaded for exact
    # change-set binding.  Loading it before restoration would reject the expected transient
    # mixed v3 state at the crash boundary.
    _validate_change_set_binding(root, journal, new_manifest, new_v3)
    _cleanup_journal(root, journal)


def _finish_cleanup(root: Path, journal: dict[str, Any]) -> None:
    current = _new_manifest_from_staging(root, journal)
    current_v3 = _new_v3_from_staging(root, journal)
    _validate_staging(root, journal, current, current_v3)
    _validate_backup(root, journal)
    for item in _snapshot_files(current, current_v3).values():
        _verify_descriptor(_check_file(root, item["path"], allow_missing=False), item)
    _cleanup_journal(root, journal)


def _validate_backup(root: Path, journal: dict[str, Any]) -> None:
    _check_ancestors(root, journal["backup_path"] + "/placeholder")
    backup = root / journal["backup_path"]
    stat = _lstat(backup)
    if stat is None or os.path.islink(backup) or not os.path.isdir(backup):
        raise RuntimeError("Living Wiki backup directory is missing or unsafe")
    allowed_files = {item["path"] for item in [*journal["updated"], *journal["deleted"]]}
    for candidate in backup.rglob("*"):
        if os.path.islink(candidate):
            raise RuntimeError("Living Wiki backup directory contains a symbolic link")
        if candidate.is_file() and candidate.relative_to(backup).as_posix() not in allowed_files:
            raise RuntimeError("Living Wiki backup directory contains an unexpected file")
    for item in [*journal["updated"], *journal["deleted"]]:
        _verify_descriptor(
            backup / item["path"],
            {
                "path": item["path"],
                "byte_size": item["old_byte_size"],
                "sha256": item["old_sha256"],
            },
        )


def recover_projection(root: Path) -> None:
    """Recover one pending projection transaction, or fail closed."""

    _check_ancestors(root, ".deeplaw/derived/tree/living-wiki-projection.journal.json")
    journal = _read_json(_journal_path(root))
    if journal is None:
        return
    _validate_journal(journal)
    if journal["phase"] == "prepare":
        current = _new_manifest_from_staging(root, journal)
        if current["manifest_sha256"] != journal["new_manifest_sha256"]:
            raise RuntimeError("Living Wiki staged transaction identity mismatch")
        current_v3 = _new_v3_from_staging(root, journal)
        _validate_staging(root, journal, current, current_v3)
        _validate_change_set_binding(root, journal, current, current_v3)
        _validate_backup(root, journal)
        _cleanup_journal(root, journal)
        return
    if journal["phase"] == "activate":
        _rollback_activation(root, journal)
        return
    if journal["phase"] == "cleanup":
        _finish_cleanup(root, journal)
        return
    raise RuntimeError("Living Wiki projection journal phase is unsupported")


def discard_transaction(root: Path, *, staging: Path, backup: Path) -> None:
    """Remove a transaction that never reached prepare (generation failed)."""

    transaction_dirs: set[Path] = set()
    for path in (staging, backup):
        stat = _lstat(path)
        if stat is None:
            continue
        if os.path.islink(path) or not os.path.isdir(path):
            raise RuntimeError("Living Wiki transaction cleanup path is unsafe")
        txn = path.parent
        if txn.parent != root / _TXN_ROOT:
            raise RuntimeError("Living Wiki transaction cleanup path escaped the Vault")
        transaction_dirs.add(txn)
    for txn in transaction_dirs:
        if os.path.islink(txn) or not txn.is_dir():
            raise RuntimeError("Living Wiki transaction cleanup path is unsafe")
        shutil.rmtree(txn)


__all__ = [
    "CHANGE_SET_SCHEMA",
    "JOURNAL_SCHEMA",
    "MANIFEST_NAME",
    "activate_projection",
    "begin_transaction",
    "build_change_set",
    "discard_transaction",
    "prepare_activation",
    "read_previous_manifest",
    "read_previous_v3",
    "recover_projection",
]
